use role sysadmin;
use warehouse slowbridge_pipeline_wh;

-- 1 Resume pipe
alter pipe slowbridge_prod_db.bronze_sch.supply_chain_pipe_prod set pipe_execution_paused=false;

select system$pipe_status['slowbridge_prod_db.bronze_sch.supply_chain_pipe_prod'];

-- 2 Resume Task
Alter task slowbridge_prod_db.silver_sch.bronze_to_silver_task resume;
Alter task slowbridge_prod_db.silver_sch.silver_to_star_task resume;

show tasks in database slowbridge_prod_db;


-- 3 resume alerts
use role accountadmin;
alter alert slowbridge_prod_db.bronze_sch.pipeline_health_alert resume;
show alerts in database slowbridge_prod_db;

-- 4 Resume dynamic TABLES
use role sysadmin;
ALTER DYNAMIC TABLE SLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_BASE RESUME;
ALTER DYNAMIC TABLE SLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_INVENTORY_TURNOVER RESUME;
ALTER DYNAMIC TABLE SLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_ORDER_FULFILLMENT RESUME;
ALTER DYNAMIC TABLE SLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_SHIPMENT_DELAYS RESUME;
ALTER DYNAMIC TABLE SLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_SUPPLIER_PERFORMANCE RESUME;

-- start ingesting data

-- 5 Verify Row Counts
SELECT 'RAW_ORDERS' AS TBL, COUNT(*) AS CNT FROM SLOWBRIDGE_PROD_DB.BRONZE_SCH.RAW_ORDERS
UNION ALL SELECT 'STG_ORDERS', COUNT(*) FROM SLOWBRIDGE_PROD_DB.SILVER_SCH.STG_ORDERS
UNION ALL SELECT 'DIM_CUSTOMER', COUNT(*) FROM SLOWBRIDGE_PROD_DB.SILVER_SCH.DIM_CUSTOMER
UNION ALL SELECT 'DIM_PRODUCT', COUNT(*) FROM SLOWBRIDGE_PROD_DB.SILVER_SCH.DIM_PRODUCT
UNION ALL SELECT 'DIM_SHIPMENT'. COUNT(*) FROM SLOWBRIDGE_PROD_DB.SILVER_SCH.DIM_SHIPMENT
UNION ALL SELECT 'DIM_SUPPLIER', COUNT(*) FROM SLOWBRIDGE_PROD_DB.SILVER_SCH.DIM_SUPPLIER
UNION ALL SELECT 'DIM_WAREHOUSE', COUNT(*) FROM SLOWBRIDGE_PROD_DB.SILVER_SCH.DIM_WAREHOUSE
UNION ALL SELECT 'FACT_ORDERS', COUNT(*) FROM SLOWBRIDGE_PROD_DB.SILVER_SCH.FACT_ORDERS
UNION ALL SELECT 'DEAD_LETTER', COUNT(*) FROM SLOWBRIDGE_PROD_DB.SILVER_SCH.DEAD_LETTER
UNION ALL SELECT 'AGG_BASE', COUNT(*) FROM SLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_BASE
UNION ALL SELECT 'AGG_INVENTORY_TURNOVER', COUNT(*) FROM SLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_INVENTORY_TURNOVER
UNION ALL SELECT 'AGG_ORDER_FULFILLMENT', COUNT(*) FROM SLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_ORDER_FULFILLMENT
UNION ALL SELECT 'AGG_SHIPMENT_DELAYS', COUNT(*) FROM SLOWBRIDGE_PROD_DB.GOLD_SCH. AGG_SHIPMENT_DELAYS
UNION ALL SELECT 'AGG_SUPPLIER_PERFORMANCE', COUNT(*) FROM SLOWBRIDGE_PROD_DB.GOLD_SCH.AGG_SUPPLIER_PERFORMANCE;

-- 6 Verify Secure Views
SELECT * FROM SLOWBRIDGE_PROD_DB.SERVING_SCH.VW_INVENTORY_TURNOVER;
SELECT * FROM SLOWBRIDGE_PROD_DB.SERVING_SCH.VW_ORDER_FULFILLMENT;
SELECT * FROM SLOWBRIDGE_PROD_DB.SERVING_SCH.VW_SHIPMENT_DEALYS;
SELECT * FROM SLOWBRIDGE_PROD_DB.SERVING_SCH.VW_SUPPLIER_PERFORMANCE;